### PR TITLE
chore: introduce dogfooding

### PR DESCRIPTION
**Pull request by benoitf**
Add image using official jekyll image
Add vale inside the image (can use vale path/to/asciidoc file to validate language)

Add devfile using devfile v2
 - 2 VS Code extensions: asciidoc and vale to see problems when editing blog posts

image

Add PR check publication to surge.sh

### CODE REVIEW

**Comment by themr0c** [comment]
Very nice!

**Comment by themr0c** [comment]
It doesn't work on  https://workspaces.openshift.com#https://github.com/eclipse-che/blog/tree/introduce-dogfooding

```
Failed to resolve a devfile. Failed to request factory resolver: "401 Unauthorized" returned by "/api/scm/resolve?repository=https://github.com/eclipse-che/blog/tree/introduce-dogfooding&file=.che/che-editor.yaml".
```

**Comment by benoitf** [comment]
@themr0c for sure the devfile is a devfile v2 relying on DevWorkspaces and image is assuming the tooling and the user are using the same container

**Review by l0rd — APPROVED** [review]
LGTM. I have tested on my local Che instance and it worked just fine.

image

**Pull request merged**
