### PR TITLE
Create preview.yaml

### PR DESCRIPTION
**Pull request by ibuziuk**
GitHub action that will coment preview URL e.g. `https://pr-check-${{ github.event.pull_request.number }}-che-blog.surge.sh/` - https://pr-check-51-che-blog.surge.sh/

### CODE REVIEW

**Review by l0rd — COMMENTED** [review]
I am ok to merge that if it works but I think the code should go [here](https://github.com/eclipse-che/blog/blob/main/.github/workflows/publish-surge-pr-check.yml#L62) to avoid duplication (the env variable `DEPLOY_DOMAIN` has the surge preview link).

**Comment by ibuziuk** [comment]
@l0rd I want to test this approach without touching surge flow for now and update it separately later on

**Comment by l0rd** [comment]
> @l0rd I want to test this approach without touching surge flow for now and update it separately later on

Ok. I am ok to merge this PR in any case if it adds value but there are couple of things I want to make sure we are ok:
1) The preview link is already present in the PR (although not super visible so I am +1 to add a comment): 
image
2) I was expecting the workflows introduced in your branch to be executed on your PR too but I don't see any comment with the preview link.

**Comment by ibuziuk** [comment]
I believe we can close it given that surge is available in PR check. Missed that completely

**Pull request closed without merging**
